version : 0.0
os: linux
files:
- source: .
  destination : /home/ubuntu/prime
hooks:
  ApplicationStart :
  - location : scripts/start.sh
    timeout : 30
    runas: ubuntu

# I added a webhook to this file as part of my troubleshooting process. The webhook tells the application how to start.